server:
  port: 8080
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/employees_db?useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: topsecret
    platform: org.hibernate.dialect.MySQLInnoDBDialect
  jpa:    hibernate:      ddl-auto: update    show-sql: true